### PR TITLE
Release 7.0.1

### PR DESCRIPTION
**Pull request by kristfal**

### CODE REVIEW

**Comment by mfazekas** [comment]
@kristfal are we releasing final from 7.0?

If so we need to keep changes backward compatible, or bump major version.

**Comment by kristfal** [comment]
Sorry, I wasn’t aware of breaking changes. If so, I’ll remove the release and we major bump.

**Comment by mfazekas** [comment]
@kristfal no problem, i don't think bumping major version is an issue. I don't see any breaking changes at the moment, altough our API esp in case of new components like Camera, UserLocation, is a bit experimental,and does require cleanup/overhaul in a lot of cases, i don't see it happing soon.

**Comment by kristfal** [comment]
Ok, then this release is OK. I was thinking we should transition to AndroidX and bump to V8. If I recall the convos from before my holidays, that was kinda critical.

**Comment by mfazekas** [comment]
> Ok, then this release is OK. I was thinking we should transition to AndroidX and bump to V8. If I recall the convos from before my holidays, that was kinda critical.

I think https://github.com/react-native-mapbox-gl/maps/pull/251 fixed jetifier npm.
So i think we can (and should) wait with direct androidx support. That means all projects using mapbox have to be converted to androidx and they might have non trivial deps not yet supporting it.

**Pull request merged**
