### PR TITLE
updated camera pitch info

### PR DESCRIPTION
**Pull request by CyrusZei**

### CODE REVIEW

**Comment by ferdicus** [comment]
hey @CyrusZei, thanks for the PR.

You have to change the comment within the code and then run the `generate` script in `package.json`.

The `md` files are the output of that script (among others).

**Comment by CyrusZei** [comment]
oh I see, will fix this in the weekend. worked with this package for a couple of months now and feel like I could contribute with the data that is missing on the docs. Thank you

**Comment by ferdicus** [comment]
Sure thing, any help is welcome 👍

**Comment by ferdicus** [comment]
Closing this, feel free to open a new PR when you have the time

**Pull request closed without merging**
