### PR TITLE
fix(location-manager): last location unavailable

### LINKED ISSUE #569: Error Last location unavailable
I have this exception sometimes, on production (I can't reproduce in dev mode)

```
Error
Last location unavailable
node_modules/@react-native-mapbox-gl/maps/javascript/modules/location/locationManager.js in call at line 21:63
    this.onUpdate = this.onUpdate.bind(this);
  }
  async getLastKnownLocation() {
    if (!this._lastKnownLocation) {
      const lastKnownLocation = await MapboxGLLocationManager.getLastKnownLocation();
      if (!this._lastKnownLocation && lastKnownLocation) {
        this._lastKnownLocation = lastKnownLocation;
      }
    }
    return this._lastKnownLocation;
```

Full log here: https://sentry.io/share/issue/8037c6ed509a496aaa969bc23698ab04/

I actually happens quite often, Android only.

Any idea ? I think it might be related to when GPS is unavailable but location permission is given or something...

### PR DESCRIPTION
**Pull request by ferdicus**
resolves #569

the issue being, that native exceptions would cause
an unhandled exception on the JS side.

.getLastKnownLocation is now wrapped within a try...catch

make sure to rebase with master, once #726 is merged and tests run smoothly before merging.

### CODE REVIEW

**Comment by ferdicus** [comment]
> On the other hand undefined/null have to be handled anyway as `lastKownLocation` can return `null` on native side.

Right, not getting anything should be fine, getting an exception on your JS usage of this is not cool I think. 

Also, I believe most users are not directly using `getLastKnownLocation` but rather use `onUpdate` of `UserLocation`, which means they may not even be aware about calling it directly/ wrapping it in a `try...catch`. 

Let me know what you think. 
Not saying this is the most elegant solution 😅

**Comment by ferdicus** [comment]
@mfazekas, did you have time to think about this?

**Comment by mfazekas** [comment]
> > On the other hand undefined/null have to be handled anyway as `lastKownLocation` can return `null` on native side.
> 
> Right, not getting anything should be fine, getting an exception on your JS usage of this is not cool I think.
> 
> Also, I believe most users are not directly using `getLastKnownLocation` but rather use `onUpdate` of `UserLocation`, which means they may not even be aware about calling it directly/ wrapping it in a `try...catch`.
> 
> Let me know what you think.
> Not saying this is the most elegant solution 😅

I hate the idea of suppressing an error without understanding when/where it's coming from.
On `onUpdate` we could catch the error from `getLastKnownLocation`. 

But since `getLastKnownLocation` can return null anyways, suppressing the error sounds acceptable, and probably the simplest.

**Comment by ferdicus** [comment]
> I hate the idea of suppressing an error without understanding when/where it's coming from.
On onUpdate we could catch the error from getLastKnownLocation.

Wholeheartedly agree, under other circumstances ....

**Pull request merged**
