### PR TITLE
Update iOS library + Potential CI fixes

### PR DESCRIPTION
**Pull request by kristfal**
Update iOS SDK to latest version. 

Regenerate yarn.lock for main repo to fix [CI issues with yarn](https://github.com/yarnpkg/yarn/issues/5865) and add lock file for example project.

### CODE REVIEW

**Comment by kristfal** [comment]
Closes #592

**Comment by ferdicus** [comment]
@kristfal, I actually have a question about this:
Why do we use two package managers to begin with? 
Locally everything seems to use `npm` however on travis we're using `yarn`.

I've to admit, that I've also added to the confusion by adding `yarn.locks` files into the mix. 😞

**Comment by mfazekas** [comment]
@ferdicus we're using yarn on travis as there were some caching related issues on travis with npm i was not able to solve, and could work around by going with yarn.
I think the issue was that because of npm package caching the example app used the old version of  the local rnmbgl, so we was not testing the latest version but some older one. I think other alternative would have been to remove full cache of npm which was slow. But not 100% about the details.

https://github.com/react-native-mapbox-gl/maps/pull/57/commits/6c20c488b84f7e459c67808d76bcb2b47d811fac

**Comment by kristfal** [comment]
That pretty much summarizes the issue. I generally have less issues with yarn, so adopted it across most of my work. 

Btw, I just double checked that we need to run the example repo without a yarn lock file due to sha integrity issues between published and locally build rnmgl package. This shouldn’t be an issue since the distributed build doesn’t depend on anything in the example folder.  

Also removed NPM lock file to avoid confusion. I’ll add package.lock to gitignore to prevent future issues/confusion with NPM and yarn.

**Comment by ferdicus** [comment]
> That pretty much summarizes the issue. I generally have less issues with yarn, so adopted it across most of my work.
> 
> Btw, I just double checked that we need to run the example repo without a yarn lock file due to sha integrity issues between published and locally build rnmgl package. This shouldn’t be an issue since the distributed build doesn’t depend on anything in the example folder.
> 
> Also removed NPM lock file to avoid confusion. I’ll add package lock to gitignore to prevent future issues/confusion with NPM and yarn.

Agreed. Does this mean, that we're going to be opinionated towards `yarn`.
If so, I would switch uses from `npm` to `yarn` -> `package.json` scripts for example

**Comment by kristfal** [comment]
It doesn’t really matter much for consumers, and not really for contributors either. Feel free to use whatever you prefer. 

The most important thing is that if you use yarn, the lock file guarantees that what you install locally will be installed identical on the CI. Not using a lock file may (under very special circumstances) produce different versions of dependency installs.

**Pull request merged**
