### PR TITLE
test(mapView): add testId when rendered outside of android and ios

### PR DESCRIPTION
**Pull request by JSanchezIO**
### Purpose:
I was writing a test that needed to validate that a map was rendered into the UI for a specific screen. However, despite having the `testID` prop available to me on the `MapView` component, I wasn't able to use `getByTestId`. It turns out that the `MapView` component doesn't render the `testID` prop if it isn't being rendered on Android or iOS.

### Solution:
- Add `testID` to the props used when `MapView` is rendered outside of Android and iOS.

### CODE REVIEW

**Comment by JSanchezIO** [comment]
This only changes the `<View />` component that gets rendered when the `<RCTMGLMapView />` isn't. So it shouldn't affect Detox tests as this `<View />` component is what gets rendered outside of devices.

**Comment by mfazekas** [comment]
> This only changes the <View /> component that gets rendered when the <RCTMGLMapView /> isn't. So it shouldn't affect Detox tests as this <View /> component is what gets rendered outside of devices.

From my reading of the code RCTMGLMapView get's rendered inside the View.

https://github.com/react-native-mapbox-gl/maps/blob/452ce86355a6993e96617cf799b98876668b79e7/javascript/components/MapView.js#L746-L764

**Comment by JSanchezIO** [comment]
Ah, I see, it may be best to then render the prop on the `<View />` when `mapView` is `null`. Nice catch!

**Comment by JSanchezIO** [comment]
Fixed, let me know if there's anything else you need.

**Pull request merged**
