### PR TITLE
Update Camera.md

### PR DESCRIPTION
**Pull request by VittoriDavide**
latitude and longitude are inverted in fitbounds method

### CODE REVIEW

**Comment by mfazekas** [comment]
@viddity  thanks for the fixes, pls note that as the first line of Camera.md says it's generated so you need to fix the issue in the source too Camera.js

**Comment by mfazekas** [comment]
@VittoriDavide thanks you also need to run `npm run generate` and i think you need to commit docs.json as well.

**Comment by mfazekas** [comment]
@VittoriDavide are you sure it's not lng, lat as documented?!

If i execute:

```ès6
this.cameraRef.fitBounds(
         [-74.135379, 40.795909],
        [-74.135449, 40.795578],
        [1.0, 0, 200, 0],
        1000.0,
      );
```

I see this:
kép

And looking at here:


-74.135379 is longitude
 40.795909 is latitude

This is confimed by both google and another site:

https://www.google.com/maps/place/40%C2%B047'45.3%22N+74%C2%B008'07.4%22W/@40.795913,-74.1355158,67m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d40.795909!4d-74.135379

https://www.latlong.net/Show-Latitude-Longitude.html

I think the names southWest and northEast are confusing.

**Comment by VittoriDavide** [comment]
Sorry, you're right, my bad, I received from the service the latitude and longitude interchanged. thank you anyway for your time :( Apologize

**Pull request closed without merging**
