### PR TITLE
performance fix: Prevent onUpdate  from firing constantly in Android

### PR DESCRIPTION
**Pull request by RichardLindhout**
GPS on Android devices seems a little flawed, it keeps changing without even a movement of the device. This code prevents this while keeping updating when something really changed.

We could probably make a different prop in the UserLocationComponent where we could listen to long-lat changes with more checks to check if the location changed significantly yes/no.

### CODE REVIEW

**Comment by ferdicus** [comment]
ok, I did some digging into the android [LocationRequest](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest) documentation.

There is the possibility to `Set the minimum displacement between location updates in meters` via the  [setSmallestDisplacement](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.html#public-locationrequest-setsmallestdisplacement-float-smallestdisplacementmeters) method.


I'm no android dev, however this seems to be just the right solution for this issue.
Maybe we should use that, before we role our own solution?

**Comment by RichardLindhout** [comment]
@ferdicus That should be the right way to move forward! Nice found!

**Comment by RichardLindhout** [comment]
Perhaps iOS has something the same 
https://developer.apple.com/documentation/corelocation/cllocationmanager/1423500-distancefilter
locationManager.DistanceFilter = smallestDisplacementMeters;

**Comment by ferdicus** [comment]
I could take a stab at setting this up tomorrow 😅 
Would be cool to have someone look over it and test it our as well, mind reviewing it when done?

**Comment by RichardLindhout** [comment]
Sure!

**Comment by ferdicus** [comment]
Takes longer (go figure...). My findings so far:
[`LocationEngineRequest.java`](https://github.com/mapbox/mapbox-events-android/blob/master/liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineRequest.java)
is the file that provides the `Builder` that is used within [`LocationManager.java`](https://github.com/react-native-mapbox-gl/maps/blob/19d509bbf4ccf6c6454d2117f005b5e7245336c8/android/rctmgl/src/main/java/com/mapbox/rctmgl/location/LocationManager.java#L63-L66)

It does not have a method called `setSmallestDisplacement`, however it is meant as a wrapper around multiple locationEngines. Therefore it does the same with `setDisplacement`.

So one can do something like this, before we implement something sane (if one wants a quick fix for the issue of high-frequency location updates):
```
 locationEngineRequest = new LocationEngineRequest.Builder(DEFAULT_INTERVAL_MILLIS) 
         .setFastestInterval(DEFAULT_FASTEST_INTERVAL_MILLIS) 
         .setPriority(LocationEngineRequest.PRIORITY_HIGH_ACCURACY) 
         .setDisplacement(5) // displacement in meters
         .build(); 
```


I'm trying to find out how it would be possible to set this up from the JS side.
So far, no clue 🤷‍♂

**Comment by ferdicus** [comment]
I've opened a PR for this #544 

Would be very grateful for a sanity check 🙇

**Comment by RichardLindhout** [comment]
Based on the feedback also working on a PR with a more customizable approach and hopefully iOS support. https://github.com/react-native-mapbox-gl/maps/pull/546

**Pull request closed without merging**
