### PR TITLE
Make iOS installation clear for newest RN 60 with autolinking.

### PR DESCRIPTION
**Pull request by dsznajder**

### CODE REVIEW

**Comment by kristfal** [comment]
Happy to merge this. Can you confirm if autolinking works with Android?

**Comment by dsznajder** [comment]
@kristfal Yes, I'm currently using it in production, and it works fine :)

**Comment by dsznajder** [comment]
@kristfal updated :)

**Comment by RichardLindhout** [comment]
For me it does not work on iOS:
```
d: framework not found Mapbox
```

**Comment by dsznajder** [comment]
@RichardLindhout 	Please clean-up whole project (I had to remove `ios/build` folder). We are using it on production and does not see any issues.
Also, have you installed pods?
```bash
cd ios && pod install
```

**Comment by RichardLindhout** [comment]
It works for me only after adding a search-path. See my pull request: https://github.com/react-native-mapbox-gl/maps/pull/382

**Pull request merged**
