### PR TITLE
Enable linear easing on map camera

### PR DESCRIPTION
**Pull request by naftalibeder**
I encountered a scenario where it would be extremely useful for the camera to be able to animate with a linear timing function, and realize that this library currently does not support that, although it's well within the ability of the camera module to do so.

Thoughts about this solution? There would be a number of ways to do this, but adding a new mode fits best within the current architecture, without needing to refactor out an easing-specific parameter.

### CODE REVIEW

**Comment by ferdicus** [comment]
Thanks for your contribution @naftalibeder 🙇🏿 

Any particular reason why you didn't add the implementation for Android as well?
We should have parity between the platforms (if that's possible with the available feature set of course). 

Additionally, it would be cool if you could add this to one of the many `example` examples where it's appropriate OR add some video to the PR showing it off for posterity. 

Thanks in advance

**Comment by naftalibeder** [comment]
@ferdicus Thanks for checking it out, and very good question! The answer is that I forgot to mention, I wanted to see if you all supported the idea, at which point I would port it over to Android. So sounds like that's a yes! I'll update when I have that ready.

At absolutely, I'd be happy to include some example video and update the demos.

**Comment by naftalibeder** [comment]
All right, Android is set up to have parity with iOS! I've attached two videos below from the iOS simulator. In both of them, the map attempts to center on a coordinate that updates every 1000ms.

*Smooth easing*

```
animationDuration={1000}
animationMode={'easeTo'}
```

https://user-images.githubusercontent.com/2423291/112871759-38078880-9085-11eb-818a-b4cd689b99d5.mov

--------------

*Linear easing*

```
animationDuration={1000}
animationMode={'linearTo'}
```

https://user-images.githubusercontent.com/2423291/112871784-3ccc3c80-9085-11eb-9d4e-430983ac5171.mov

--------------

This should also demonstrate an ideal use case - any kind of continuous motion looks a lot better with linear map movement.

Keen eyes will notice that even the linear map transition shows a very slight fluctuation at the end of each cycle. This is the point where I need to waive responsibility off to the Mapbox SDK - I don't think there's anything else we can do in this library to fix that. But compared with the ease-in-ease-out movement, I think the linear easing is a significant improvement for uses that require it.

cc @ferdicus

**Comment by ferdicus** [comment]
Looks great, thanks @naftalibeder 🙇🏿

**Pull request merged**
