### PR TITLE
iOS: fix asset image scale

### PR DESCRIPTION
**Pull request by mfazekas**
Fixes: #68 

Use imageScale from react native vs trying to figure out.

Before #1206 mapbox worked for static images without `@2x` and `@3x` suffixes.
#1206 fixed that for the case the image had same resolution as the device (so `@3x` on 3x device).

This PR should work for normal and scaled images (`@2x`...)

https://github.com/nitaliano/react-native-mapbox-gl/pull/1206

### CODE REVIEW

**Comment by mattijsf** [comment]
Hi @mfazekas I was working on another PR and when updating the generated files I was noticing that some work from this PR was reverted because the templates `RCTMGLStyle.m.ejs` and`RCTMGLStyleFactory.java.ejs` is not updated with changes from this PR.

**Comment by mfazekas** [comment]
@mattijsf  thanks i'll try to look into it.

**Comment by mfazekas** [comment]
@mattijsf #87 should fix the autogen scripts

**Comment by winseyli** [comment]
Today I migrated to this new mapbox sdk from the old one, and my markers are using the 3x asset images. Is this PR included in the latest npm? Thank you

**Comment by mfazekas** [comment]
@winseyli nope, please use npm from github or use rc4 when released.

**Pull request merged**
