### PR TITLE
Fixed issue with PointAnnotation refresh by using default native bridge, fixed types

### PR DESCRIPTION
**Pull request by hannojg**
For me the `refresh` on `PointAnnotation` didn't work. The JS invoked `UIManager.dispatchViewManagerCommand` which never reached the native component.
With this fix, I let `PointAnnotation` use the "default" native bridge implementation used everywhere else and fixed the issue (so that the commands reach the native side).

Happy to see this merged 😊 if there is anything left to do for me, just tell so!

### CODE REVIEW

**Comment by ferdicus** [comment]
hey @hannojg, can you please provide an example to test this.
Preferably something beforehand, that didn't work and something that does work.

I've tested on both Android and iOS with https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShowPointAnnotation.js

It didn't crash 👍 😄 

However, that there is the only use of `refresh` I've seen. 
Can you show me, how you're using it? 

Thanks in advance

**Comment by hannojg** [comment]
Hu, while I was creating a reproduction the refresh works suddenly just like you would expect it. I am not able to reproduce the issue anymore. Even in our production app, I tried it again using the 8.0.0-rc2 and suddenly it also works there.

So I guess the only value this PR provides is the fixed type definition for the Point Annotation class.

I will create a new PR for this.

**Comment by ferdicus** [comment]
No worries, thanks for checking it out again 👍

**Comment by ErikTillberg** [comment]
I want to add this here since I was experiencing the same problem, on 8.1.0-rc.2. I have an image loaded from the web within a PointAnnotation and was calling refresh in the onLoad method, however the PointAnnotation wasn't re-rendering with the image. I went in and added the changes from this commit into the node modules to test and it works as expected now.

**Comment by hannojg** [comment]
That's interesting! On our project the refresh thing starts also failing again 🤔 . We will try out this fix another time and see whether we can reproduce it.

**Comment by NickM00** [comment]
Experienced the same issue on my project. 
Tried various things but none of them worked, except for this fix.
I think it might be a good idea @ferdicus to reopen this issue and merge it eventually because it definitely fixes this marker issue on android.

**Comment by ferdicus** [comment]
Hey all, it would be really helpful to get a very very simple repro example I could fire up and see this failing/ working. 

Could one of you please provide that? 

Thanks in advance

**Comment by hannojg** [comment]
We have this fix in our project running with patch-package to get things working on android.
Will try to create a production in the next few days.

**Comment by anhkieet** [comment]
@hannojg  Could you show me your fix? I am facing the same issue.

**Comment by hannojg** [comment]
Diffs are:

```diff
diff --git a/node_modules/@react-native-mapbox-gl/maps/javascript/components/PointAnnotation.js b/node_modules/@react-native-mapbox-gl/maps/javascript/components/PointAnnotation.js
index b4a58e6..9f1f046 100644
--- a/node_modules/@react-native-mapbox-gl/maps/javascript/components/PointAnnotation.js
+++ b/node_modules/@react-native-mapbox-gl/maps/javascript/components/PointAnnotation.js
@@ -11,6 +11,8 @@ import {
 import {toJSONString, isFunction, viewPropTypes} from '../utils';
 import {makePoint} from '../utils/geoUtils';
 
+import NativeBridgeComponent from "./NativeBridgeComponent";
+
 export const NATIVE_MODULE_NAME = 'RCTMGLPointAnnotation';
 
 const styles = StyleSheet.create({
@@ -31,7 +33,7 @@ const styles = StyleSheet.create({
  * If you need interctive views please use MarkerView,
  * as with PointAnnotation on Android child views are rendered onto a bitmap for better performance.
  */
-class PointAnnotation extends React.PureComponent {
+class PointAnnotation extends NativeBridgeComponent(React.PureComponent) {
   static propTypes = {
     ...viewPropTypes,
 
@@ -116,7 +118,7 @@ class PointAnnotation extends React.PureComponent {
   };
 
   constructor(props) {
-    super(props);
+    super(props, NATIVE_MODULE_NAME);
     this._onSelected = this._onSelected.bind(this);
     this._onDeselected = this._onDeselected.bind(this);
     this._onDragStart = this._onDragStart.bind(this);
@@ -161,6 +163,11 @@ class PointAnnotation extends React.PureComponent {
     return toJSONString(makePoint(this.props.coordinate));
   }
 
+  _setNativeRef(nativeRef) {
+    this._nativeRef = nativeRef;
+    super._runPendingNativeCommands(nativeRef);
+  }
+
   /**
    * On android point annotation is rendered offscreen with a canvas into an image.
    * To rerender the image from the current state of the view call refresh.
@@ -168,7 +175,10 @@ class PointAnnotation extends React.PureComponent {
    */
   refresh() {
     if (Platform.OS === 'android') {
-      UIManager.dispatchViewManagerCommand(findNodeHandle(this), 'refresh', []);
+      this._runNativeCommand(
+        'refresh',
+        this._nativeRef,
+      );
     }
   }
 
@@ -190,7 +200,7 @@ class PointAnnotation extends React.PureComponent {
       coordinate: this._getCoordinate(),
     };
     return (
-      <RCTMGLPointAnnotation {...props}>
+      <RCTMGLPointAnnotation ref={(nativeRef) => this._setNativeRef(nativeRef)} {...props}>
         {this.props.children}
       </RCTMGLPointAnnotation>
     );

**Comment by mfazekas** [comment]
@hannojg would you open this pr again?! The issue seems to be valid but i cannot merge as the source was removed.

**Comment by hannojg** [comment]
Reopening is disabled for me 🤔  the button is greyed out

**Comment by hannojg** [comment]
can't find the source on my machine, sorry.

**Comment by anhkieet** [comment]
> can't find the source on my machine, sorry.
> The diffs posted were the only changes I made if I remember correctly

Thanks @hannojg I have changed my code based on your diffs. And It works

**Comment by mfazekas** [comment]
@hannojg NP, i've opened a PR with the same diffs https://github.com/react-native-mapbox-gl/maps/pull/1062

**Pull request closed without merging**
