### PR TITLE
Support AndroidX

### PR DESCRIPTION
**Pull request by jshearer**
This project has dependencies on `com.android.support` that were causing trouble with androidx. I understand that this change is backwards incompatible and will only work with RN 0.60.x+, but maybe it'll be a helpful starting point in getting others unblocked.

To test drive this, you can do:

```
"@react-native-mapbox-gl/maps": "jshearer/maps",
```
in your `package.json`.

I honestly don't have that much familiarity with Java, so I'm not sure if this is a complete solution, or even the correct one.

Relates to #163

### CODE REVIEW

**Comment by dsznajder** [comment]
I can confirm that Android form this PR works. But still running into issues with iOS 😕

**Comment by jshearer** [comment]
I mean, this wasn't supposed to address iOS issues, and a new issue is probably a better place to discuss, but what issues are you having?

**Comment by dsznajder** [comment]
@jshearer I get sth like `cannot read StyleURL of undefined`. Seems like maybe I messed up with autolinking. I will investigate the problem more and maybe came back with solution. I know that it isn't iOS related. Just making a note for future people :)

**Comment by jshearer** [comment]
Ok cool, thanks :) I'll check it out too and see what I find.

**Comment by dsznajder** [comment]
@jshearer Ok, I've messed up autolinking :) iOS works fine :)

**Comment by DavidKHahn** [comment]
@dsznajder hello, were you able to get Android build to work properly? I had a similar issue with the StyleURL on the Android side.  If so how were you able to get the fix?

**Comment by mattijsf** [comment]
Looks good. I would make use of the previously present safeExtGet with fallback values function to allow the root project to override used versions with `annotationVersion` / `appCompatVersion` / `vectordrawableVersion`

**Comment by mattijsf** [comment]
The example app needs to be updated to AndroidX as well, which is why the integration tests are currently failing.

**Comment by dsznajder** [comment]
@DavidKHahn Yes I've already upgraded my app to 60.3. What issues you have? Have you added linking properly? I've updated also docs so take a look :)

**Comment by zeljkoX** [comment]
Thanks for this PR.
I confirm that it is working on v0.60.

Issues that I am experiencing are that custom marker is not displayed, the default one is displayed instead, and the map is zoomed out.

**Comment by mustafaskyer** [comment]
this working @react-native: 0.60.3  ✅

**Comment by mfazekas** [comment]
@jshearer as per #610 we'd like to upgrade to androidx for 8.0.0, would you like to update your PR?!

**Pull request closed without merging**
