### PR TITLE
Feature/get cluster leaves

### PR DESCRIPTION
**Pull request by krakz999**
## Description

Adds `getClusterLeaves` method to ShapeSource that allows you to retrieve the features from a cluster by the cluster's ID. 

Supports pagination using the `limit` and `offset` parameters. If you don't need pagination, just use `point_count` as `limit` and `0` as `offset`.

Example: 

```
shapeSourceRef.current.getClusterLeaves(clusterId, numberOfResults, offset);
```

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [ ] I updated the documentation `yarn generate`
* [ ] I mentioned this change in `CHANGELOG.md`
* [x] I updated the typings files (`index.d.ts`)
* [ ] I added/ updated a sample  (`/example`)

### CODE REVIEW

**Comment by ferdicus** [comment]
@krakz999 , thank you very much for opening this 🙇🏿 

If it's not too much to ask, could you go the extra mile and finish those three open checks on the PR description? 

Let me know if you need any help with those/ if there are questions

**Comment by ferdicus** [comment]
@krakz999, need any assistance?

**Comment by evgenTraytyak** [comment]
any updates?

**Comment by evgenTraytyak** [comment]
https://github.com/react-native-mapbox-gl/maps/pull/1411

**Comment by ferdicus** [comment]
closing in favor of #1411 

sorry @krakz999

**Pull request closed without merging**
