### PR TITLE
Add telemetry dependency to avoid android 11 crash

### LINKED ISSUE #1286: [Android] Crash when opening a screen with map in Android 11
**Describe the bug**  
Every time I open a screen that has a map, the application crashes. 
It seems this has to do with the latest version of Android. Android 11. 
This crash did not occur before the last update of the operating system.

**To Reproduce**  
Open a screen with a map.

**Expected behavior**  
The screen should show the content (map).

**Actual behavior**  
Crashes the app when we try to open a screen with a map.

**Screenshots** 
 Screen Shot 2021-03-19 at 2 13 38 PM

Screenshot_20210319-140733_Vibemap

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 11
 - Device: Samsung Galaxy A51
 - Emulator/ Simulator: No
 - Dev OS: [e.g. OSX 11.0.1, Win10]
 - react-native-mapbox-gl Version 8.1.0
 - React Native Version: 0.63.4

**Additional context**  
Logs:

```
Fatal Exception: java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10306 does not have android.permission.READ_PHONE_STATE.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3706)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3670)
       at com.mapbox.android.telemetry.m0.h(:10)
       at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(:21)
       at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(:25)
       at com.mapbox.mapboxsdk.maps.m.a(:8)
       at com.mapbox.rctmgl.components.mapview.c.<init>(:45)
       at com.mapbox.rctmgl.components.mapview.b.<init>()
       at com.mapbox.rctmgl.components.mapview.RCTMGLAndroidTextureMapViewManager.createViewInstance(:11)
       at com.mapbox.rctmgl.components.mapview.RCTMGLAndroidTextureMapViewManager.createViewInstance()
       at com.facebook.react.uimanager.ViewManager.createViewInstance()
       at com.facebook.react.uimanager.ViewManager.createView()
       at com.facebook.react.uimanager.m.a(:34)
       at com.facebook.react.uimanager.v0$e.execute(:23)
       at com.facebook.react.uimanager.v0$a.run(:114)
       at com.facebook.react.uimanager.v0.j(:53)
       at com.facebook.react.uimanager.v0.j()
       at com.facebook.react.uimanager.v0$j.b(:31)
       at com.facebook.react.uimanager.e.a()
       at com.facebook.react.modules.core.g$d.a(:46)
       at com.facebook.react.modules.core.a$a$a.doFrame(:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:740)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### PR DESCRIPTION
**Pull request by Joao360**
## Description

Fixes #1286

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [ ] I updated the documentation `yarn generate`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`index.d.ts`)
* [ ] I added/ updated a sample  (`/example`)

### CODE REVIEW

**Comment by ferdicus** [comment]
Please correct me if I'm wrong,   
this would however pull in the dependency even if you are not in need of it:
* older version of Android
* newer version of the mapbox-android-SDK

Therefore I'd rather delegate this to a change within the Installation guide, 
giving people the choice to install it as they need it.

**Comment by arabold** [comment]
I'm not a MapBox SDK expert, but I don't think @ferdicus  concerns hold up:
* older versions of Android don't crash, sure. But they still benefit from the bug fixes and improvements in the updated telemetry package (and so does iOS). This change would only ensure that we need at least version `6.1.0` that contains important Android 11 fixes.
* not sure what you mean with "newer" version of the mapbox-android-SDK. Currently the `build.gradle` locks it to `9.1.0` which is already comparatively old. The only reason why we need to update the telemetry version is because the SDK uses an even older version in its dependencies. It pulls 6.0.x if I remember correctly. So, the change in this PR doesn't really _add_ anything, it just fixes a broken/outdated dependency.

So, from my understanding, this is a legitimate and necessary fix for the React Native package. It simply ensures that the package is compatible with the latest version of Android out of the box. That's nothing I would want to delegate to any developers to configure. In fact, the only way I could make it work was by patching `@react-native-mapbox-gl/maps` manually.

**Comment by ferdicus** [comment]
Maybe I misunderstood the issue at hand 🤔 

Can someone give me a way to repo this easily?   
Does this also work with emulator or only physical devices?

**Comment by arabold** [comment]
I've created a test repo here: https://github.com/arabold/react-native-mapbox-gl-maps-test

It is basically just a `create-react-native-app` with Multidex enabled and an updated OkHttp3 version to address some debugger issues 🙄 🤷 . All optional Android permissions have been removed. The `App.js` itself is a copy-paste of the example code from this repo.

Without the corrected telemetry module the app thrown and error on startup. If you add the dependency to the `build.gradle` of `@react-native-mapbox-gl/maps` it works out of the box.

As a reference, the issue reported in the `mapbox-gl-native-android` library: https://github.com/mapbox/mapbox-gl-native-android/issues/425

**Comment by ferdicus** [comment]
Thanks @arabold for setting up the test repo - I was able to successfully reproduce the issue at hand. 🙇🏿 

I stay with my initial assessment of this PR. 
The crash can be avoided by pulling in the telemetry dependency.  
It is not required to have it hardcoded for all users of this repo. 

If one is using any combination of Android OS and this lib that cause a crash, 
one can add the dependency to their `android/app/gradle.build`. 
No need to patch this libs `build.gradle` files.  

Message in the installation guide about this behaviour would be appreciated as a replacement of this PR. 

Cheers

**Comment by arabold** [comment]
I understand and thanks for your feedback. However, I was not able to get this working by updating my own `build.gradle`. Only patching (using `patch-package`) worked in my original tests. But I admit I haven't tried the same in the test repository. I'll give it a shot when I can (will be out for a couple of days). If it works by updating the local `build.gradle` (as opposed to patching), I agree that it is probably unnecessary to fix it here.

**Comment by arabold** [comment]
I managed to give this a quick test this morning. Indeed it seems it is sufficient to add the telemetry module to the `app/build.gradle` without patching the `react-native-mapbox-gl/maps` package.
```
dependencies {
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0'
}
```

Not sure why this didn't work when I tested it a while back. Maybe I just didn't properly recompile first or whatever... I guess this PR can be closed then. Although quite frankly I would have hoped to have this as part of the default build settings to make it easy for new devs, I understand if you prefer having people configure their dependencies manually. 

Note that this already affects Expo v41 users and will soon break all new Android releases, when API 30 (Android R) becomes the required minimum target version in [in August 2021](https://github.com/facebook/react-native/issues/30814).

**Comment by Joao360** [comment]
I finally had some time to add that dependency to `app/build.gradle` without patching the package and it works for me as well.

I'll close this PR but I also think this could be part of the default build settings to avoid debugging hours.

Thank you for all your feedback!

**Comment by ferdicus** [comment]
Thanks for your support and effort in contributing, although it didn't make into `master` this time please don't let that discourage you to open PRs/ issues in the future. 
I've adjusted the Installation guide for Android to reflect this. 

Thanks 🙇🏿

**Comment by ferdicus** [comment]
I'm reverting my stance on this after seeing more and more people encountering this =>  especially with the new addition of Expo users under this repos umbrella. 

Will add it as a default dependency

**Pull request closed without merging**
