### PR TITLE
Fix _runPendingNativeCommands in NativeBridgeComponent

### PR DESCRIPTION
**Pull request by frankrowe**
The `_runPendingNativeCommands` method in NativeBridgeComponent does not work.

MapView is a subclass of NativeBridgeComponent. It overrides the method `_runNativeCommand` with a different signature.

When `super._runPendingNativeCommands` is called from MapView, it calls `_runNativeCommand` with the parent signature, but the child method is called because `this` refers to the child.

To fix this, I renamed MapView `_runNativeCommand` to `_sendNativeCommand`. I also fixed an if condition in `_runPendingNativeCommands`.

To test this call a MapView method from componentDidMount:
```
async componentDidMount() {
  const p = await this._map.getPointInView([0, 0])
  console.log('point', p)
}
```

### CODE REVIEW

**Comment by frankrowe** [comment]
Ok. There must be some other bug then. When `_runNativeCommand` is called from `_ _runPendingNativeCommands`, it is not getting the correct arguments.

**Comment by frankrowe** [comment]
hi @mfazekas. are you able to reproduce the bug with this? If the !nativeRef condition is fixed so that `_runPendingNativeCommands` actually runs, you should be able to reproduce

**Comment by mfazekas** [comment]
> hi @mfazekas. are you able to reproduce the bug with this? If the !nativeRef condition is fixed so that `_runPendingNativeCommands` actually runs, you should be able to reproduce

I was not able to repro the issue, i've tried with the example code posted above on ios it worked with just the `!nativeRef` fix.

**Comment by mfazekas** [comment]
@frankrowe i've merged just the `!nativeRef` fix via #306 let me know if you see an issue with that.

**Pull request closed without merging**
