### PR TITLE
Improve TypeScript typings

### PR DESCRIPTION
**Pull request by ascorbic**
I've done an overhaul of the typings, tightening up the definitions and removing errors. I'd recommend applying #439 before this one if possible, as that also edits index.d.ts.

### CODE REVIEW

**Comment by kristfal** [comment]
I didn’t check the details, but overall this looks very good! Merging.

**Comment by ascorbic** [comment]
Rebased and conflicts resolved.

**Comment by jlo1** [comment]
@kristfal any plans to create a new release tag with this PR's change any time soon?

**Comment by kristfal** [comment]
@jlo1 I'll do it today.

**Pull request merged**
