### PR TITLE
Feature/replace deprecated api

### PR DESCRIPTION
**Pull request by SimonErm**
This PR replaces the deprecated 
```
 public void receiveCommand(ReactScrollView scrollView, int commandId, @Nullable ReadableArray args)
```
with
```
 public void receiveCommand(ReactScrollView scrollView, String commandName, @Nullable ReadableArray args)
```
Furthermore this PR fixes the Issue from  #972, which happened because the JS-Side already passed the commandName instead of the id.

### CODE REVIEW

**Comment by ferdicus** [comment]
hi @SimonErm, thanks for opening this PR 🙇 

Could you please link to the documentation detailing the deprecation, I would like to read up on it. 📚 

Cheers

**Comment by mfazekas** [comment]
@SimonErm 👍 
One concern with replace deprecated api-s is that it limits the compatibility of RNMBGL regarding older RN releases. 

I think String commands was introduced in RN 0.61. 

https://github.com/facebook/react-native/commit/3cae6fa950eed54bccccf61a28c0e85d5a004c6c

So this change would make RNMGL RN 0.61+ only. This needs to be documented and probably requires a version bump.

**Comment by SimonErm** [comment]
@ferdicus it's marked at the sources https://github.com/facebook/react-native/blob/0e442d1c0292117fa1d6d6be703496a27008a470/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManager.java#L199
> facebook/react-native@3cae6fa

@mfazekas you're right, i did't thought about that

**Comment by mfazekas** [comment]
@SimonErm Thanks, I've updated the code so PointANnotation Refresh works now. https://github.com/react-native-mapbox-gl/maps/pull/1062

I'm not sure at what point we want to drop RN 0.60. (i do have an RN 0.60 project)

**Pull request closed without merging**
