### PR TITLE
:label: (MarkerView) Adding MarkerView Type

### LINKED ISSUE #829: MarkerView MIssing from Types in 8.0.0?
**Describe the bug**
I'm trying to use MarkerView in 8.0.0 using Typescript but I don't see it in the types. 

**To Reproduce**
Review index.d.ts in 8.0.0 and see it is missing.

**Expected behavior**
I'd like it to be in the exported types so I can see it in Typescript. 

**Screenshots**
I can still use it, but it shows up as an error: 

image

**Versions (please complete the following information):**
 - Platform: Android, iOS 8.0.0
 - react-native-mapbox-gl Version 8.0.0
 - React Native Version 0.61.5

**Additional context**
Using Typescript.

### PR DESCRIPTION
**Pull request by solinehayes**
Fixes #829

### CODE REVIEW

**Comment by ferdicus** [comment]
Hey there 👋 
Thanks for taking the time to contribute 🙇 

Having that said, could you please split this in tow PRs please.
One being the MarkerView changes and another with linting the `index.d.ts`?

Thanks you very much. 🙏

**Comment by ferdicus** [comment]
ping @solinehayes

**Comment by AmauryLiet** [comment]
hey there, jumping in

I believe that #849 gives a more exact typing (reusing PointAnnotationProps) - what about closing this one (#840) in favor of it @ferdicus?

**Comment by ferdicus** [comment]
Hey, wanted to give @solinehayes some time to react to the feedback first. 
@solinehayes, let me know if you want to dispute this - I will close this in favor of #849 as @AmauryLiet suggested

**Comment by AmauryLiet** [comment]
definitely makes sense @ferdicus :) we happen to be coworkers with @solinehayes so I knew she agrees with the outcome :P

**Pull request closed without merging**
