### PR TITLE
Create Type-Definitions for Camera

### PR DESCRIPTION
**Pull request by svrin**
This provides typescript information for the Camera Object.

I do not know whether its already a good point to update the typescript definition, but I think it helps to use the project. I'm glad to help if the Camera object will change up to release.

### CODE REVIEW

**Comment by mfazekas** [comment]
@svrin Thanks,

Ideally we'd generate index.d.js automatically. I think we have all metadata needed - you can doublecheck at  https://github.com/react-native-mapbox-gl/maps/blob/master/docs/docs.json,

we seems to have some incomplete index.d.js generator at:
https://github.com/react-native-mapbox-gl/maps/blob/master/scripts/templates/index.d.ts.ejs

see 
https://github.com/nitaliano/react-native-mapbox-gl/pull/1526

**Comment by svrin** [comment]
Ah okay, thanks for the info.

I will try then to use the generator, please close then the PRs (opened another one, before seeing your comment)

**Comment by doomsower** [comment]
@mfazekas 
I was going to contribute some defs after I settle mapbox into my project but then I saw this. In my opinion, generating typescript defs from doc file is just wrong. It gives you neither typechecking no code assistance while writing them. How do you even import NativeSyntheticEvent from react-native in this doc file?

**Comment by mfazekas** [comment]
>generating typescript defs from doc file is just wrong. It gives you neither typechecking no code assistance while writing them. 

@doomsower Can you ellaborate, with concrete examples?

What i meant that in our code we have documentation which contains the description of types:
https://github.com/react-native-mapbox-gl/maps/blob/712284c2d476cd08e6a915196f66dea82d52922a/javascript/components/Camera.js#L240-L260

We do have a parser already that parses these documentations and generates the wiki/etc files. All the info extracted is here:
https://github.com/react-native-mapbox-gl/maps/blob/712284c2d476cd08e6a915196f66dea82d52922a/docs/docs.json#L212-L270

>  How do you even import NativeSyntheticEvent from react-native in this doc file?

I guess doc comments could describe that callbacks parameters are NativeSyntheticEvent, then index.d.ts.ejs could use that to generate the neccesary imports.

**Comment by doomsower** [comment]
Sorry, I cannot provide concrete examples. I have just started to consume this library and see the gaps in typedefs. I just don't know what linting/tooling do you use to write these docs. What if you type ` {Arry<Number>}` instead of ` {Array<Number>}` in these docs? What would generator spit out in `index.d.ts`? Good typings should reference underlying `@types/react` and `@types/react-native` definitions (like refs or synthetic events) and I don't know how good the generator is and how hard it is to keep it up-to-date with these defs.

The best solution is of course to rewrite the js part into typescript, and use something like typedoc.
Another easier option is to maintain `index.d.ts` manually and write docs there, then generate docs from this file and not from js files.

But I have no right to complain, because I don't have time to contribute anything bigger than minor ts fixes. For now I'll just stick with custom typings in my project.

**Comment by svrin** [comment]
@mfazekas 

I used yesterday to try a little bit to generate a index.d.ts from the docs.json.

But the arrayOf param type is missing some essential information:
 - First their subtype (like number)
 - Second the length information

Similiar the func param type (like onPress) is missing the information about their parameters.

Is there a possibility to get the information into the docs.json ?

**Comment by mfazekas** [comment]
@svrin Let me look into `arrayOf`, react-docgen seems to handle it just we strip this info. On PropTypes.func, unfortunatley it's [not handled by react-docgen]( https://github.com/reactjs/react-docgen/issues/141), i look into if it's easy to parse jsDoc and apply types from there -

**Comment by mfazekas** [comment]
@svrin See #154 it parses arrayOf and also `@params` and `@returns` from PropType.func docs.

https://github.com/react-native-mapbox-gl/maps/blob/ab1ac2a9587419cd3ace12abb1b12a3924785b70/javascript/components/ShapeSource.js#L92-L99

https://github.com/react-native-mapbox-gl/maps/blob/ab1ac2a9587419cd3ace12abb1b12a3924785b70/docs/docs.json#L3266-L3291

**Comment by svrin** [comment]
@mfazekas Thanks, this really helps (have a look at https://github.com/wettercom/react-native-mapbox-gl/blob/master/index.d.ts)

Could you also have a look why the layerIDs parameter (f.e. in queryRenderedFeaturesInRect) is specified as Array but without its subtype?

**Comment by mfazekas** [comment]
> d you also have a look why the layerIDs parameter (f.e. in queryRenderedFeaturesInRect) is specified as Array but without its subtype?

It's because the docs just specify Array= without element types.

https://github.com/react-native-mapbox-gl/maps/blob/70b9437066723d40459113696a24143c2fac85e9/javascript/components/MapView.js#L350-L360

**Comment by svrin** [comment]
Hmm, so should we model them as any[] ? Or could we improve the docs?

**Comment by mfazekas** [comment]
@svrin sure if we can improve the docs we should do that.

**Comment by henninghall** [comment]
Fixed by https://github.com/react-native-mapbox-gl/maps/pull/230

**Pull request closed without merging**
