### PR TITLE
Make it clear PointAnnotation is deprecated

### PR DESCRIPTION
**Pull request by arnaudambro**
related to [#54](https://github.com/react-native-mapbox-gl/maps/issues/54): I spent to much time trying to fix a bug on a PointAnnotation... if it was clearer, it would have been much better !

### CODE REVIEW

**Comment by arnaudambro** [comment]
after a `npm run generate`, here is my error stack

```
> @react-native-mapbox-gl/maps@7.0.0-rc3 generate /Users/arnaudambro/Pro/__libraries/mapbox-react-native
> node ./scripts/autogenerate

Generating RCTMGLStyle.h
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/arnaudambro/Pro/__libraries/mapbox-react-native/example/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLStyle.h'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at forEach (/Users/arnaudambro/Pro/__libraries/mapbox-react-native/scripts/autogenerate.js:315:6)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/arnaudambro/Pro/__libraries/mapbox-react-native/scripts/autogenerate.js:307:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @react-native-mapbox-gl/maps@7.0.0-rc3 generate: `node ./scripts/autogenerate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @react-native-mapbox-gl/maps@7.0.0-rc3 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arnaudambro/.npm/_logs/2019-07-11T12_22_30_086Z-debug.log
```

I tried to look for a solution but I did not yet...

**Comment by mfazekas** [comment]
@arnaudambro it looks you need to cd into examples and run npm install (or yarn install)

**Comment by arnaudambro** [comment]
Oh I missed it, sorry about that...

There is another error now, it seems that I need to install a CLI but I don't know which one and how:
```
/bin/sh: documentation: command not found
```

**Comment by mfazekas** [comment]
`npm install -g documentation`

https://www.npmjs.com/package/documentation

**Comment by arnaudambro** [comment]
@mfazekas I tried to look for `shell command documentation` on google, and `documentation` is not a good keyword, I couldn't find... I should have looked for `npm documentation`, sorry about that !

anyway, I think the PR is good now, tell me if not !

thanks

**Pull request merged**
