### PR TITLE
Ts example

### PR DESCRIPTION
**Pull request by mfazekas**
Added a TS component to our example app, so editing/testing type definitions is easier

### CODE REVIEW

**Comment by mattijsf** [comment]
No plans to migrate to TS codebase yet? 😅 (I would actually like that)

**Comment by mfazekas** [comment]
> No plans to migrate to TS codebase yet? 😅 (I would actually like that)

I'm not against it, but i don't really have the resources for it ATM.  I guess the only counter-argument could be that it raises the bar for contributors.

**Comment by mattijsf** [comment]
It could raise the bar but if we only use the type-checking capabilities it is basically just JS + type annotations. In personal projects I only strictly only use the type-checking features from TypeScript not other language features. I tried Flow for a while but at the time (1.5 years ago) switched to TypeScript for type-checking due to Flow being somewhat immature / buggy still. Never regretted that choice.

TS could at the same time also improve quality of contributions in the sense that there is better validation available. Documentation would benefit from it as well.

But time / resources would definitely be a problem. There is quite an existing codebase that is not easily converted at once. But I also think the two (JS / TS) can co-exist and that components can gradually be migrated to TS. It's also something the community can easily contribute to.

**Comment by mfazekas** [comment]
@mattijsf thanks for the comment, I'll open an issue for Typescript, where we can discuss the roadmap see #921. I think having a TS component in examples is a start in that direction.

**Pull request merged**
