### PR TITLE
Prevent crash when applying invalid Styles

### PR DESCRIPTION
**Pull request by calypsow777**
Currently, when we give incorrect styles to layers it causes Mapbox and the app to crash.
This is an inconvenient behaviour if we want to let users define their own custom layers.
This PR contains 2 changes :

- I've added try catch in the addStyles() of all the layers in Java. This is to counter the problem when we give the wrong value for a style (e.g. a string instead of a number) and conversions fail. We could refactor to do it once in RCTLayer. I didn't do it for iOS because it doesn't seem to cause crashes.

- I've added a try catch in the getStyle() of AbstractLayer. This is to counter the problem when we give a style name that doesn't exist (e.g. iconSi instead of iconSize).

### CODE REVIEW

**Comment by calypsow777** [comment]
Same as #261 but in a different branch.

**Comment by kristfal** [comment]
Hey,

thanks for contributing. I’m honestly not sure if this is something we should do. This would also mean silently swallowing errors in production and not show layers, which to some projects (say those used in operation critical navigation) may be more dangerous than crashing the app because they could lead to a false sense of security. My own company is in this position.

Opinion: If you want your users to customize styles, you should build in pre-validation in the JS side instead of depending on the library to handle errors for you.

**Comment by mfazekas** [comment]
I agree with @kristfal. I think an acceptable way to handle this would be some error manager, that could have callbacks on the js side to allow apps to customize what happens in case of such errors.

**Comment by kristfal** [comment]
Closing. See comments above for rationale.

**Pull request closed without merging**
