### PR TITLE
Added Style component to for adding layers / sources from style json

### PR DESCRIPTION
**Pull request by mattijsf**
Simple component that is able to load style json and transforms it into supported components.

`<MapboxGL.Style json={json|url}>`

Inspired by https://github.com/react-native-mapbox-gl/maps/issues/846

### CODE REVIEW

**Comment by mfazekas** [comment]
@mattijsf the CI is failing now, i  think there is a test which checks for exported symbols, that must be adjusted.

**Comment by mattijsf** [comment]
@mfazekas Indeed, sorry for that. I was already looking at it!

**Comment by mattijsf** [comment]
Also added some tests for this via https://github.com/react-native-mapbox-gl/maps/pull/867

**Comment by mfazekas** [comment]
@mattijsf great! Thanks much! 👍

**Pull request merged**
