### PR TITLE
Add support for userLocationAnchorPoint

### PR DESCRIPTION
**Pull request by dorthwein**

### CODE REVIEW

**Comment by dorthwein** [comment]
Adding userAnchorPoint param functionality

**Comment by dorthwein** [comment]
This allows users to set an x, y coordinate to anchor the maps current position.  Was not able to implement similar functionality on android unfortunately as the camera system works differently/I don't really know java well enough.

**Comment by kristfal** [comment]
Hey, build is failing, so that needs to be fixed. In general, I’m not super fond of implementing features that only work on one platform. Can you open a ticket upstream in the native mapbox library for native iOS support?

**Comment by kristfal** [comment]
Closing due to no response and broken build. Feel free to reopen with a green build.

**Pull request closed without merging**
