### PR TITLE
Remove all instances of isTelemetryEnabled

### PR DESCRIPTION
**Pull request by kristfal**
Since the feature is not available on Android, I suggest we remove it fully from the code base.

### CODE REVIEW

**Comment by woodpav** [comment]
Do you know why this was removed? It was a useful method.

**Comment by kristfal** [comment]
As the initial message says, the method is no longer available on Android.

**Comment by woodpav** [comment]
Well yeah but why not?

**Comment by kristfal** [comment]
We don’t control which APIs are made available in the underlying native SDKs. That is something you need to address directly with mapbox. This is a community project where we aim to wrap the native iOS and Android SDKs for RN.

**Pull request merged**
