### PR TITLE
Add course to the location event

### LINKED ISSUE #1213: [Android] User location heading is not correct
**Background**
On Android, the heading property reported by `UserLocation.onUpdate` is not correct because it is not the direction in which the phone is pointing (as it is implemented on iOS), but it is in fact the user course (the direction in which the device/user is travelling).

This happens because on android the `Location.getBearing()` is called instead of `LocationComponent.getCompassEngine().getLastHeading()`.

**Difference between course and heading**
It seems that users are confusing and intermixing the terms heading and course, and this difference in value of heading for iOS and Android is a good example of that. **A good explanation of the differences between heading and course can be found here: http://www.chrobotics.com/library/heading-course-and-crab-angle**

**Suggested fix**
We suggest that we add a new property `course` on the `location.coordinates` object. This will have correct/valid values for both iOS and Android.

Since the heading value on Android is wrongly displaying the course (as described above), we suggest that we add a comment to the documentation about this to make users aware of the bug. This is a short term fix to make users aware of it.

To fix the heading bug in Android is a bigger/separate task. We therefore suggest that we create a separate issue and eventually a PR for this in the native Android repository. Once heading is added in the native layer, then we can also correct the heading bug here in react native repository.

We have created a PR to add the course at: https://github.com/react-native-mapbox-gl/maps/pull/1209

### PR DESCRIPTION
**Pull request by andrei-tofan**
This PR fixes the issue described in https://github.com/react-native-mapbox-gl/maps/issues/1213.

_Edit ferdicus:_
resolves #1213

### CODE REVIEW

**Comment by ferdicus** [comment]
hey @andrei-tofan, thanks for this PR. 

Just so I understand it correctly, this would be iOS exclusive, because the Android api doesn't provide a way to get the `heading` - because it's not public. 

Correct?

**Comment by andrei-tofan** [comment]
We've created an issue to explain the fixing detail: https://github.com/react-native-mapbox-gl/maps/issues/1213, also updated the description of the pr.

**Comment by andrei-tofan** [comment]
@ferdicus are the comments we made in the issue clear or do you have any questions?

What do you think about this change?

**Comment by ferdicus** [comment]
I'll get back to you tomorrow - I didn't have time to go through all of it atm unfortunately. 

Cheers 🍻

**Review by mfazekas — APPROVED** [review]

**Comment by ferdicus** [comment]
Thanks for the extensive comments and explanation @andrei-tofan. 

Looks good 👍🏿

**Pull request merged**
