### PR TITLE
ShapeShource#onPress e.nativeEvent is now deprecated, use e.features

### PR DESCRIPTION
**Pull request by mfazekas**
Currently in ShapeSource/VectorSource onPress returns a single feature, we also cannot get location of press.
```es6
onPress(e) {
    const feature = e.nativeEvent.payload;
    ...
}
```

With the new version the above works, but deprecated, and you can now access all the features that were at the point of click via: `features`  (the old `payload` only contained the first feature) There is also additional coordinates and point describing the location of the press
```es6
onPress({features, coordinates, point}) {
    ...
}
```

Fixes: #611

### CODE REVIEW

**Comment by mfazekas** [comment]
@kristfal @mattijsf  any feedback on this change?!

**Comment by tanguy64** [comment]
Thanks @mfazekas for improving this function ! 
I tried it with ShapeSource - does the goal of the features arg is to get all the leaves of a clustered point when pressed ? 
I successfully have the feature properties of a single point. But when I press a clustered point I cannot retrieve the different leaves of it. I still have the same as before eq. the properties with point_count and cluster=true...

**Comment by mfazekas** [comment]
@tanguy64 the `features` does contains multiple features in case you don't have clustering enabled but you have multiple features at the place of click. 

We could allow ways to return cluster details - [childrenOfCluster](https://docs.mapbox.com/ios/api/maps/5.7.0/Classes/MGLShapeSource.html#/c:objc(cs)MGLShapeSource(im)childrenOfCluster:)

**Comment by tanguy64** [comment]
Ok that's very clear thank you. Indeed I have clustering enabled. And childrenOfCluster or leavesOfCluster are exactly what I am looking for zooming to the bounds of a clustered point children onPress and getting the children data.

**Comment by bboure** [comment]
@mfazekas I think typing is broken here after this change
https://github.com/react-native-mapbox-gl/maps/blob/master/index.d.ts#L707

**Comment by mfazekas** [comment]
@bboure pls submit a PR, typing is lagging behind the library, sorry

**Pull request merged**
