### PR TITLE
Improve `filter` and `LayerBaseProps` TypeScript typings

### PR DESCRIPTION
**Pull request by anfriis**
- It is currently not supported to set a filter with nested arrays e.g. `filter={['!', ['has', 'point_count']]}`.
- `getVisibleBounds()` returns bounds/region so it should have the same type as `visibleRegion` in `RegionPayload`

### CODE REVIEW

**Comment by anfriis** [comment]
Could this be merged please? Should be fairly straightforward to merge in :)

**Comment by kristfal** [comment]
More typescript fixes :) keep em up.

**Comment by anfriis** [comment]
Sure thing :) Just resolved the conflict

**Comment by kristfal** [comment]
Many thanks. Merged to master.

**Pull request merged**
