### PR TITLE
feat(example): type ShowMap

### PR DESCRIPTION
**Pull request by ferdicus**
Converting `ShowMap` to typescript.
On the way adding a (opinionated) `eslintrc` for the example folder that supports `ts/tsx`.
Additionally added `locationManager` types to our definition file

Looking forward to your review

### CODE REVIEW

**Comment by ferdicus** [comment]
> I think this is a great first step to converting things to TS, but I do question if we should be migrating the examples specifically to TS. 

Ha, not first step :D
I merely continued where @mfazekas started.

> I think it makes sense to have some examples in TS so people know how to work with this library when using TS, but I worry that it may make things more confusing for people who are less familiar with TS or are not using TS in their project. Would it make sense for us to leave some samples in plain JS and some in TS? Maybe separate out the TS and JS examples?

I understood the conversion of `/example` as a dryrun to convert the main project.

Also, to be quite honest, I'm not sure where to start with root 😅 

I asked some question in the open [TS conversion ticket](https://github.com/react-native-mapbox-gl/maps/issues/921#issuecomment-644076811) with no concrete answers yet.

**Comment by mfazekas** [comment]
> Also, to be quite honest, I'm not sure where to start with root 😅
> 
> I asked some question in the open [TS conversion ticket](https://github.com/react-native-mapbox-gl/maps/issues/921#issuecomment-644076811) with no concrete answers yet.

I think it's good to have some of the examples as TS and some of them as plain JS. Regarding starting converting the main code, i guess we should start with a simpler component like `UserLocation` or `Camera`, then we'll see the issues?

**Comment by ClayC-WeatherBug** [comment]
> > Also, to be quite honest, I'm not sure where to start with root 😅
> > I asked some question in the open [TS conversion ticket](https://github.com/react-native-mapbox-gl/maps/issues/921#issuecomment-644076811) with no concrete answers yet.
> 
> I think it's good to have some of the examples as TS and some of them as plain JS. Regarding starting converting the main code, i guess we should start with a simpler component like `UserLocation` or `Camera`, then we'll see the issues?

I'm still getting familiar with the code so I would follow whatever you guys think. I'd either pick a spot that seems easy, or just next time you are working on a component or whatever then convert it.

**Comment by ferdicus** [comment]
> > > Also, to be quite honest, I'm not sure where to start with root 😅
> > > I asked some question in the open [TS conversion ticket](https://github.com/react-native-mapbox-gl/maps/issues/921#issuecomment-644076811) with no concrete answers yet.
> > 
> > 
> > I think it's good to have some of the examples as TS and some of them as plain JS. Regarding starting converting the main code, i guess we should start with a simpler component like `UserLocation` or `Camera`, then we'll see the issues?
> 
> I'm still getting familiar with the code so I would follow whatever you guys think. I'd either pick a spot that seems easy, or just next time you are working on a component or whatever then convert it.

Totally agree, my biggest hang-up is the initial setup.
* Where and how are we storing type definitions?
* how is this going to replace the current `index.d.ts` file?
* compilation setup for TS (correct `tsconfig`)
* babel/ metro stuff
* hopefully not breaking things for users 😅 

I'll try to set something up the coming friday based on the `example` projects setup.
Happy for any input/ feedback

**Comment by ClayC-WeatherBug** [comment]
> > > > Also, to be quite honest, I'm not sure where to start with root 😅
> > > > I asked some question in the open [TS conversion ticket](https://github.com/react-native-mapbox-gl/maps/issues/921#issuecomment-644076811) with no concrete answers yet.
> > > 
> > > 
> > > I think it's good to have some of the examples as TS and some of them as plain JS. Regarding starting converting the main code, i guess we should start with a simpler component like `UserLocation` or `Camera`, then we'll see the issues?
> > 
> > 
> > I'm still getting familiar with the code so I would follow whatever you guys think. I'd either pick a spot that seems easy, or just next time you are working on a component or whatever then convert it.
> 
> Totally agree, my biggest hang-up is the initial setup.
> 
> * Where and how are we storing type definitions?
> * how is this going to replace the current `index.d.ts` file?
> * compilation setup for TS (correct `tsconfig`)
> * babel/ metro stuff
> * hopefully not breaking things for users 😅
> 
> I'll try to set something up the coming friday based on the `example` projects setup.
> Happy for any input/ feedback

Yeah, I hear you on that. I just did this in an existing react native project. I've not done it on a package that gets distributed yet though.

> Where and how are we storing type definitions?
I believe the common convention for this is to put them in a __types__ folder these days. 

>how is this going to replace the current index.d.ts file?
I would think that as we convert types and add them we could remove the placeholders that are in the index.d.ts file until eventually we remove it.

> compilation setup for TS (correct tsconfig)
I think the TSConfig we have is probably okay, but we can always adjust it. The beauty of typescript is that we can leave a very easy/friendly/loose config for now and tighten things later as we get more coverage and comfort in the project. The only thing that I think might be different is we likely need to exclude or not explicitly include our __types__ folder from the files that get published to yarn and create a separate deployment of the types to a `@types` package. That way people who don't care about TS don't have to care about it or include it if they don't want it. Their code doesn't get bigger because we want to use TS.

> babel/ metro stuff
I think this will likely be generally the same as the example project, but I could be wrong.

> hopefully not breaking things for users 😅
😅

I think some of these questions might be answered if we check out some other react native projects as well and see what common convention is in larger react native projects.

**Comment by ferdicus** [comment]
heard all your feedback, gonna take it to heart ❤️ 

in the meantime, lemme merge this 😄

**Pull request merged**
