### PR TITLE
[iOS] Fixed handling of lineDashPattern and iconTextFitPadding values

### PR DESCRIPTION
**Pull request by mattijsf**
Fixes: #83

### CODE REVIEW

**Comment by mattijsf** [comment]
@kristfal Thanks! I'd be happy to contribute more so yes that would be great!

**Comment by kristfal** [comment]
@mattijsf great! Let me know when you've accepted and I'll bump your privileges for this repo

**Comment by mattijsf** [comment]
@kristfal I accepted. Let me know if I can help with anything else!

**Comment by kristfal** [comment]
Great, you should now have write access :)

**Pull request merged**
