### PR TITLE
Add `maxBounds` property

### PR DESCRIPTION
**Pull request by ascorbic**
This PR adds support for a `maxBounds` property, similar to the JS version. It uses the native setLatLngBoundsForCameraTarget method.

See #372 and #422

### CODE REVIEW

**Comment by kristfal** [comment]
Thanks a lot for your contribution! This looks great for Android, but we should add similar support for iOS along with an example in the example app. Would you be able to do this?

**Comment by ascorbic** [comment]
I might be able to at some point, but I did this for a specific Android project and can't justify the time to add iOS support. It's more complicated, because iOS doesn't have built-in support for restricting bounds. I'll see if I can do it in my own time.

**Comment by ascorbic** [comment]
OK, I managed to get the time to add iOS support and a screen in the sample app

**Comment by kristfal** [comment]
Great! Thanks for this. Merging

**Comment by DhavalKakadiya** [comment]
Hey @ascorbic , Thanks for this. 
But I am facing one issue. can you please help me to resolve that? 
When I am using **maxBounds** property. It can restrict that area but I couldn't zoom the map in iOS.

If you have any idea about that then can you please let me know?

Thanks for the help in advance!!

**Comment by ascorbic** [comment]
Afraid not, @DhavalKakadiya

**Comment by adityareddyav** [comment]
Hi @ascorbic 
Is there any workaround to this if not a direct way of resolving it?

**Comment by mattijsf** [comment]
@adityareddyav Have a look at https://github.com/react-native-mapbox-gl/maps/issues/642

**Pull request merged**
