### PR TITLE
Add types for geoutils

### PR DESCRIPTION
**Pull request by jeremybarbet**
I added typescript definition for geoutils and also added options parametre often allowed through `@turf/helpers`.

I'm not sure if there is any test I can run through to make sure it's all good, let me know if there is!

### CODE REVIEW

**Comment by jeremybarbet** [comment]
Sorry for pinging @kristfal, @mfazekas nobody looking at PRs?

**Comment by kristfal** [comment]
Hey. Sorry. We are, but this one slipped past my attention. Thanks for pinging. Merging this now.

**Comment by jeremybarbet** [comment]
Great! thank you

**Comment by artemkolotilkin** [comment]
Seeing 2 typos in this MR: lines 126-127 - `otions` instead of `options`.  I can create a new MR to fix those.

**Comment by jeremybarbet** [comment]
That's a good catch @artemkolotilkin Feel free to create a fix for it!

**Pull request merged**
