### PR TITLE
Fix crash when layerIndex is greater than the number of layers

### PR DESCRIPTION
**Pull request by frankrowe**
This fixes a crash that happens when a layerIndex is higher than the amount of layers on the map.

Since there is no way to get the number of layers in this library like there is in the native SDKs, using layerIndex is difficult. This change makes using layerIndex a little more forgiving.

### CODE REVIEW

**Comment by kristfal** [comment]
I think this is ok, but I think we should at least log a warning when this happens.

**Comment by calypsow777** [comment]
Any news on this?

**Comment by kristfal** [comment]
Thanks for this. As said earlier, I'm inclined to print a warning here. 

We've been discussing hard vs soft error handling for styles in general, and while I favour hard crashes, I can see the issue here.

Happy to merge if we print a yellowbox warning here, but I think just silently handling this will cause more confusion than benefits.

**Comment by calypsow777** [comment]
Any idea how to go about it?

I see the link between Java and js here https://github.com/react-native-mapbox-gl/maps/blob/59238cd3c9a21cbc875989d7efcec7ecc7a9db74/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/layers/RCTMGLFillExtrusionLayerManager.java#L51
But I don't see how to pass warnings between native code and js. :thinking: 

I'm asking because I've never done native stuff and I don't know if this is a trivial problem someone could do in 3 minutes or if it requires some refactoring.

**Comment by frankrowe** [comment]
@kristfal Added warnings

**Pull request merged**
