### PR TITLE
Detox test

### PR DESCRIPTION
**Pull request by mfazekas**
This is work in progress, unfortunately there seems to be blocking issues on gettin detox work on CI:

1. Accessibility doesn't seems to work with travis & 10.1, 10.2 osx images 
   see https://travis-ci.community/t/xcode-helper-is-not-trusted-for-accessibility/206 
   in the logs i see this logline: 
   `[90m2019-05-05 08:16:09.186 SimulatorBridge[26180:49721] AccessibilityUpstraemProvider: Failed to look up service (com.apple.iphonesimulator.accessibility.upstream): 1102`
   the i see travis timeouting
2. We cannot run UI tests on anroid/linux as x86 emulator's (which uses virtualization) deosn't run on travis.

### CODE REVIEW

**Comment by kristfal** [comment]
Ok, thanks for the test. I know Detox should work on AppCenter (we used to run on it), but they don’t seem offer any free plans for OS. CircleCI does, both for Mac OS and Linux. May want to give that a go. I’m quite swamped for the next few weeks, but after that, I’m happy to work on this and contribute more here. GJ so far btw!

**Comment by ferdicus** [comment]
Hey @kristfal I was curious by what you said, because I was looking into e2e testing on AppCenter. Unfortunately they seem to support Appium (among others), however detox seems to be missing: [related ticket/ feature request](https://github.com/Microsoft/appcenter/issues/262) :(

**Comment by kristfal** [comment]
We ran it as part of the build process, there are some examples out there. Works if your build + E2E tests are less than 1h in total.

**Comment by ferdicus** [comment]
ah, cool - ok, I thought we were looking for strictly on device tests.

**Comment by johnhiggs** [comment]
@kristfal could you point me to an example please of where detox can work with app center?

**Comment by kristfal** [comment]
https://github.com/patniko/detox-appcenter is a starting point. You'll likely need to adjust it a bit.

**Pull request closed without merging**
