### PR TITLE
Add allowUpdates prop on Camera

### PR DESCRIPTION
**Pull request by naftalibeder**
## Description

Adds an optional `allowUpdates` boolean prop to `Camera` which, if false, causes the camera to return early before communicating with the native camera module.

This is intended for situations where the map is not visible (including if the app is in the background), and it would be preferable to avoid moving the camera - and therefore fetching new tiles, or causing the markers on the map to change - without actually hiding the map, which can cause undesirable behavior when the map reappears.

The only reasonable alternative is to "freeze" all props _before_ sending them to `Camera`, which adds a bit more complicated logic to the enclosing app.

## Checklist

- [X] I have tested this on a device/simulator for each compatible OS
- [X] I formatted JS and TS files with `yarn lint`
- [X] I updated the documentation `yarn generate`
- [X] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

## Screenshot OR Video

TODO

### CODE REVIEW

**Comment by naftalibeder** [comment]
@ferdicus What do you think about this? We've been working around this for a pretty long time, and I think this would greatly simplify how an app needs to handle this situation. I know this prop doesn't have a corresponding config in the native modules, but it is specific to React logic (e.g. you can't "early return" in declarative code).

**Comment by naftalibeder** [comment]
Yep, we do:

```
<Camera
  ...
  allowUpdates={appStateIsActive || pictureInPicture}
/>
```

(The picture-in-picture conditional is for Android.)

**Comment by ferdicus** [comment]
thanks

**Comment by ferdicus** [comment]
@naftalibeder, this is [failing tests](https://github.com/react-native-mapbox-gl/maps/runs/4209078557?check_suite_focus=true) after merge (sorry, didn't catch it earlier - forked PRs don't run actions 😞 ):

**Comment by naftalibeder** [comment]
Sorry about that - fixed [here](#1637).

Maybe the default PR checklist should include `yarn run unittest`?

**Comment by ferdicus** [comment]
> Sorry about that - fixed [here](#1637).
> 
> Maybe the default PR checklist should include `yarn run unittest`?

Good thing you mentioned it - I've added an additional todo in #1631 (sorry.... 😞 )

**Pull request merged**
