### PR TITLE
Required dependencies needed for running examples

### PR DESCRIPTION
**Pull request by systemlevel**
Went through examples setup.  These were required deps to make the examples work.

Required dependencies needed for running examples without initial errors popping up.

### CODE REVIEW

**Comment by ferdicus** [comment]
I'd like to challenge this a bit, as I was playing around with the example app (albeit two weeks ago) and didn't see the dependency issues.
* did you encounter these errors for all scenes/ examples?
* were you on Android or iOS or does it apply to both?

**Comment by mfazekas** [comment]
Also have you used yarn or npm?!

**Comment by systemlevel** [comment]
@ferdicus Let me run through it again.  The packages were missing and then onces I installed the indicated packages examples worked without a hitch.  I'll try again from a clean start.  

@mfazekas I used yarn for installed example packages.  Not good? Only NPM?

**Comment by ferdicus** [comment]
Sorry, I can't reproduce this:
* I'm also using `yarn`
* was building for physical android (`master`) - worked ✅ 
* was building for simulated ios (`master`) - worked ✅ 

> I'll try again from a clean start.
I guess that'll be it, probably some gradle dep shenanigans 👍

**Pull request closed without merging**
