### PR TITLE
WIP: Web support

### PR DESCRIPTION
**Pull request by mfazekas**
Initial web support.

Just the structure, not much is working for now. Usage:

```
cd example
expo start:web --web
```

Only `Camera` and `MapView` has web impl, and even those do not provide much at the moment.

kép

### CODE REVIEW

**Comment by mfazekas** [comment]
Currently i'm blocked on this issue:

```
./gradlew :app:bundleReleaseJsAndAssets
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


error Unable to resolve module `mapbox-gl` from `../javascript/web/MGLModule.js`: mapbox-gl could not be found within the project.
Error: Unable to resolve module `mapbox-gl` from `../javascript/web/MGLModule.js`: mapbox-gl could not be found within the project.
```

On android we wouldn't need to bundle the files in `web` directory, i'll somehow need to tell the bundler that.

**Comment by mfazekas** [comment]
Even stanger ci issue: 

https://travis-ci.org/github/mfazekas/maps-1/jobs/688519947
```

error Unable to resolve module `react-native/Libraries/Image/AssetRegistry` from `../assets/heading.png`: react-native/Libraries/Image/AssetRegistry could not be found within the project.

```

**Comment by ferdicus** [comment]
Hey @mfazekas, should we maybe put this on the backburner?
Feel that we're spreading too thin, taking on too many things as well. 

There is also TypeScript 😅

**Comment by mfazekas** [comment]
@ferdicus once we've managed to release 8.1 final I'd like to get it into the repo.

It would be just a starting point, so if there is interest then the community can finalize it. It's more contributor friendly as it's pure js.

**Comment by ferdicus** [comment]
👍 

I've created a Milestone to keep track of all the things that are required for `release 8.1`
Can we link tickets for it to that milestone so we have more transparency of what need to be done in order to release.

**Comment by natew** [comment]
Just wanted to revive this to get an idea of timeline, it seems the project has advanced quite a bit since with Typescript and a few releases.

This would be quite cool!

**Comment by Daavidaviid** [comment]
Any news about the web support ? Is it in another repository ?

**Pull request closed without merging**
