### PR TITLE
Add compass positioning and margins

### PR DESCRIPTION
**Pull request by anlai2**
This PR features:
- Added numeral enum for compass position. 
   https://docs.mapbox.com/ios/api/maps/5.0.0/Enums/MGLOrnamentPosition.html
  (iOS only) Have not found gravity values for corners to work with [setCompassGravity](https://docs.mapbox.com/android/api/map-sdk/5.1.2/com/mapbox/mapboxsdk/maps/UiSettings.html#setCompassGravity-int-)
- Added use of compass margins (multiplied android values by 2 for better device scaling)
- Added info to docs.

### CODE REVIEW

**Comment by kristfal** [comment]
This looks very good. One thought: Can you update the Android native code to use devicePixelRatio rather than a flat 2x multiplier?

**Comment by anlai2** [comment]
Good idea. 

Any idea why `self.compassView.hidden` is not being evaluated for when I'm checking it in compassViewPosition and compassViewMargins in iOS code? This causes compassEnabled to be required in order to disable it.

**Comment by kristfal** [comment]
Build is failing due to type errors. Please fix and I’ll merge.

**Comment by anlai2** [comment]
Fixed errors, thanks @kristfal for pointing it out.

**Comment by kristfal** [comment]
Merged. Thanks a lot for your contribution.

**Pull request merged**
